# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('phone_extension', models.CharField(max_length=8)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
