# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_address_neighborhood'),
        ('logistics', '0005_auto_20170802_0234'),
    ]

    operations = [
    ]
