# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 19:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0008_auto_20170816_1957'),
        ('logistics', '0007_auto_20170802_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='waypoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waypoints.Waypoint'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{7,15}$')]),
        ),
    ]
