# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_auto_20170807_0620'),
        ('logistics', '0008_auto_20170816_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.Client'),
        ),
    ]
