# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_auto_20170816_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='third_party_reference',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
