# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_shipment_third_party_reference'),
        ('logistics', '0009_shipment_client'),
    ]

    operations = [
    ]
