# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 15:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_merge_20170828_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 7 y 15 dígitos.', regex='^\\+?1?\\d{7,15}$')]),
        ),
    ]
