# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_auto_20170901_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
