# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_shipment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.Carrier'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_address', to='logistics.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_contact', to='logistics.Contact'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_address', to='logistics.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_contact', to='logistics.Contact'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='waybill_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
