# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0026_create_dhl_entity'),
        ('user_profiles', '0011_add_secret_to_all_clients'),
        ('logistics', '0014_create_dhl_carrier_postals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=50, verbose_name='Numero de Orden del Cliente')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.Client')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waypoints.Waypoint')),
            ],
        ),
    ]
