# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tosp_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrettoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secrettoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
