# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 20:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Contacto')),
                ('contact_last_name', models.CharField(blank=True, max_length=255, verbose_name='Apellido del Contacto')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Contacto')),
                ('deleted', models.BooleanField(default=False)),
                ('entity', models.CharField(blank=True, max_length=35, verbose_name='Entidad')),
                ('holiday_time_end', models.TimeField(blank=True, null=True, verbose_name='Fin Horario Dia Festivos')),
                ('holiday_time_start', models.TimeField(blank=True, null=True, verbose_name='Inicio Horario Dia Festivos')),
                ('lunch_break', models.BooleanField(default=False, verbose_name='Pausa Almuerzo')),
                ('lunch_time_end', models.TimeField(blank=True, null=True, verbose_name='Fin Pausa Almuerzo')),
                ('lunch_time_start', models.TimeField(blank=True, null=True, verbose_name='Inicio Pausa Almuerzo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Punto de Entrega')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('open_holidays', models.BooleanField(default=False, verbose_name='Abierto Dias Festivos')),
                ('open_saturday', models.BooleanField(default=False, verbose_name='Abierto Sabados')),
                ('saturday_time_end', models.TimeField(blank=True, null=True, verbose_name='Fin Horario Sabados')),
                ('saturday_time_start', models.TimeField(blank=True, null=True, verbose_name='Inicio Horario Sabados')),
                ('time_open', models.TimeField(null=True, verbose_name='Horario Apertura')),
                ('time_close', models.TimeField(null=True, verbose_name='Horario Cierre')),
                ('volume_limit', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Limitación Volumétrica')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics.Address')),
                ('carriers', models.ManyToManyField(to='logistics.Carrier')),
            ],
        ),
    ]
