# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0002_auto_20170727_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='fedex_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Id del Punto en API de Fedex'),
        ),
    ]
