# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 07:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0003_waypoint_fedex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='contact_phone_extension',
            field=models.CharField(blank=True, max_length=8, verbose_name='Extensión Teléfono del Contacto'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='contact_last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Apellido del Contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del Contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=4, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='fedex_id',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, verbose_name='Id del Punto en API de Fedex'),
            preserve_default=False,
        ),
    ]
