# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0005_auto_20170802_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='fedex_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Id del Punto en API de Fedex'),
        ),
    ]
