# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0007_auto_20170802_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='Longitud'),
        ),
    ]
