# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0008_auto_20170816_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='estafeta_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Id del Punto en API de Estafeta'),
        ),
    ]
