# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0009_waypoint_estafeta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='carriers',
            field=models.ManyToManyField(blank=True, to='logistics.Carrier'),
        ),
    ]
