# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0010_auto_20170831_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Teléfono del Contacto'),
        ),
    ]
