# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models
from waypoints.models import WaypointGroup, Waypoint

def forwards_func(apps, schema_editor):
    """ Create all the required groups in the database.

    """
    db_alias = schema_editor.connection.alias
    god_group = WaypointGroup.objects.using(db_alias).create(name='Todos')
    waypoints = Waypoint.objects.using(db_alias).all()
    god_group.waypoints = waypoints
    god_group.save()

def reverse_func(apps, schema_editor):
    """ Revert changes made in forwards_func
    """
    db_alias = schema_editor.connection.alias
    WaypointGroup.objects.using(db_alias).get(name='Todos').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0012_waypointgroup'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
