# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0013_waypoint_god_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Entidad')),
            ],
        ),
        migrations.AddField(
            model_name='waypoint',
            name='entity_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waypoints.Entity'),
        ),
    ]
