# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0015_transfer_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='entity',
        ),
    ]
