# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0016_remove_waypoint_entity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waypoint',
            old_name='entity_link',
            new_name='entity',
        ),
    ]
