# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0017_auto_20171017_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypointgroup',
            name='entities',
            field=models.ManyToManyField(blank=True, to='waypoints.Entity'),
        ),
    ]
