# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 23:16
from __future__ import unicode_literals

from django.db import migrations

def change_waypoints_to_entities(apps, schema_editor):
    WaypointGroup = apps.get_model('waypoints', 'WaypointGroup')
    Entity = apps.get_model('waypoints', 'Entity')
    db_alias = schema_editor.connection.alias
    entities = Entity.objects.using(db_alias).all()
    for group in WaypointGroup.objects.using(db_alias).all():
    	group.waypoints.clear()
    	if group.name == 'Todos':
    		group.entities = entities
    	group.save()

def reverse_func(apps, schema_editor):
    WaypointGroup = apps.get_model('waypoints', 'WaypointGroup')
    Entity = apps.get_model('waypoints', 'Entity')
    Waypoint = apps.get_model('waypoints', 'Waypoint')
    db_alias = schema_editor.connection.alias
    waypoints = Waypoint.objects.using(db_alias).all()
    for group in WaypointGroup.objects.using(db_alias).all():
    	group.entities.all().delete()
    	if group.name == 'Todos':
    		group.waypoints = waypoints
    	group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0018_waypointgroup_entities'),
    ]

    operations = [
	    migrations.RunPython(change_waypoints_to_entities,reverse_func),
    ]
