# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0019_change_group_waypoints_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypointgroup',
            name='waypoints',
        ),
    ]
