# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0020_remove_waypointgroup_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='external_id',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Id del Punto en API Externa'),
        ),
    ]
