# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 01:20
from __future__ import unicode_literals

from django.db import migrations

def migrate_external_ids(apps, schema_editor):
    Waypoint = apps.get_model('waypoints', 'Waypoint')
    db_alias = schema_editor.connection.alias
    waypoints = Waypoint.objects.using(db_alias).all()
    for waypoint in waypoints:
    	if waypoint.entity.name == 'Fedex':
    		waypoint.external_id = waypoint.fedex_id
    	elif waypoint.entity.name == 'Estafeta':
    		waypoint.external_id = waypoint.estafeta_id
    	waypoint.save()

def remove_external_ids(apps, schema_editor):
	Waypoint = apps.get_model('waypoints', 'Waypoint')
	db_alias = schema_editor.connection.alias
	waypoints = Waypoint.objects.using(db_alias).all()
	for waypoint in waypoints:
		waypoint.external_id = ''
		waypoint.save()

class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0021_waypoint_external_id'),
    ]

    operations = [
	    migrations.RunPython(migrate_external_ids,remove_external_ids),
    ]
