# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0023_auto_20171021_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='estafeta_id',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='fedex_id',
        ),
    ]
