# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 02:30
from __future__ import unicode_literals

from django.db import migrations

def create_entity(apps, schema_editor):
    Entity = apps.get_model('waypoints', 'Entity')
    WaypointGroup = apps.get_model('waypoints', 'WaypointGroup')
    db_alias = schema_editor.connection.alias
    fedex, created_fedex = Entity.objects.using(db_alias).get_or_create(name='Fedex')
    estafeta, created_estafeta = Entity.objects.using(db_alias).get_or_create(name='Estafeta')
    circle_k, created_circle_k = Entity.objects.using(db_alias).get_or_create(name='CircleK/Extra')
    god_group = WaypointGroup.objects.using(db_alias).get(name='Todos')
    if created_fedex:
        god_group.entities.add(fedex)
    if created_estafeta:
        god_group.entities.add(estafeta)
    if created_circle_k:
        god_group.entities.add(circle_k)
    god_group.save()

def remove_entity(apps, schema_editor):
	Entity = apps.get_model('waypoints', 'Entity')
	db_alias = schema_editor.connection.alias
    # It's not cool to delete all entities when there are still points that need them.
	# Entity.objects.using(db_alias).get(name='Fedex').delete()
	# Entity.objects.using(db_alias).get(name='Estafeta').delete()
	Entity.objects.using(db_alias).get(name='CircleK/Extra').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0024_auto_20171021_0223'),
    ]

    operations = [
	    migrations.RunPython(create_entity,remove_entity),
    ]
