# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_load_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='activo',
            new_name='active',
        ),
    ]
