# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 03:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_auto_20170705_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.CharField(blank=True, max_length=512, verbose_name='Dirección de Facturación'),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_conditions',
            field=models.TextField(blank=True, verbose_name='Condiciones de Facturación'),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Facturación'),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono de Facturación'),
        ),
        migrations.AddField(
            model_name='client',
            name='comercial_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Contacto Comercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='comercial_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Contacto Comercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='comercial_contact_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Teléfono del Contacto Comercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='finance_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Contacto de Finanzas'),
        ),
        migrations.AddField(
            model_name='client',
            name='finance_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Contacto de Finanzas'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='client',
            name='logistics_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Contacto de Lógistica'),
        ),
        migrations.AddField(
            model_name='client',
            name='logistics_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Contacto de Lógistica'),
        ),
        migrations.AddField(
            model_name='client',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('Magento', 'Magento'), ('Prestashop', 'Prestashop'), ('Shopify', 'Shopify'), ('WOO Commerce', 'WOO Commerce'), ('Propio', 'Propio'), ('Otro', 'Otro')], max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, max_length=12, verbose_name='RFC'),
        ),
    ]
