# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_auto_20170713_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='comercial_contact_email',
            new_name='commercial_contact_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='comercial_contact_name',
            new_name='commercial_contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comercial_contact_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='platform_type',
        ),
        migrations.AddField(
            model_name='client',
            name='commercial_contact_phone',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='El número de telefono tiene que tener el siguiente formato: "+999999999" El número tiene que tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Contacto Comercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='ecommerce_platform',
            field=models.CharField(blank=True, choices=[('Magento', 'Magento'), ('Prestashop', 'Prestashop'), ('Shopify', 'Shopify'), ('WOO Commerce', 'WOO Commerce'), ('Propietary', 'Propietaria'), ('Other', 'Otro')], max_length=200, verbose_name='Plataforma de e-commerce'),
        ),
    ]
