# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_auto_20170713_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC'),
        ),
    ]
