# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0012_waypointgroup'),
        ('user_profiles', '0009_auto_20170901_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, to='waypoints.WaypointGroup'),
        ),
    ]
